Changes to allow spaces in model directory and working directory

diff --git a/convert_script_s2b b/convert_script_s2b
--- a/convert_script_s2b
+++ b/convert_script_s2b
@@ -178,6 +178,10 @@ function abspath {
     fi
 }
 
+# The directory which actually contains convert_script_s2b
+CVRT_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+echo "Called from: ${CVRT_SCRIPT_DIR}"
+
 # The default location for the spineml-2-brahms temporary files and input model(s)
 SPINEML_2_BRAHMS_DIR=$HOME"/spineml-2-brahms"
 
@@ -255,6 +259,7 @@ while getopts w:srAgm:o:e:p:d:c:t:n:a:vVD\? opt
 do
     case "$opt" in
         w)  SPINEML_2_BRAHMS_DIR="$OPTARG"
+	    echo "Set SPINEML_2_BRAHMS_DIR from command line argument to ${SPINEML_2_BRAHMS_DIR}"
             ;;
         s)  REBUILD_SYSTEMML="false"
             ;;
@@ -267,6 +272,7 @@ do
         m)  MODEL_DIR="$OPTARG"
             ;;
         o)  OUTPUT_DIR="$OPTARG"
+	    #OUTPUT_DIR=`echo $OUTPUT_DIR | sed 's/ /\\ /g'`
             ;;
         e)  EXPT_NUM="$OPTARG"
             ;;
@@ -390,7 +396,7 @@ fi
 
 # Preflight the model - note we're outputting the contents of the PROPERTY_CHANGES
 # array which contains --property_change=a:b:3 type options.
-spineml_preflight -e $OUTPUT_MODEL_DIR"/"$EXPERIMENT "${PROPERTY_CHANGES[@]}" "${DELAY_CHANGES[@]}" "${CONSTANT_CURRENTS[@]}" "${TVARYING_CURRENTS[@]}"
+spineml_preflight -e "${OUTPUT_MODEL_DIR}/${EXPERIMENT}" "${PROPERTY_CHANGES[@]}" "${DELAY_CHANGES[@]}" "${CONSTANT_CURRENTS[@]}" "${TVARYING_CURRENTS[@]}"
 if [ "$?" -ne "0" ]; then
     echo "Failed to preflight the model." >&2
     exit -1
@@ -408,7 +414,7 @@ elif [ $(uname) = 'Windows_NT' ] || [ $(uname) = 'MINGW32_NT-6.1' ]; then
 else
     OS='OSX'
 fi
-echo "OS: $OS"
+echo "OS: ${OS}"
 
 # Now to test to see if we have a pre-compiled/package managed
 # toolspace? If NOT then we check if we need to compile using the
@@ -417,20 +423,26 @@ echo "OS: $OS"
 if [ -d /usr/lib/spineml-2-brahms ]; then
     # We have a pre-compiled spineml-2-brahms
     echo "You have a pre-compiled spineml-2-brahms namespace installed."
-    echo "Copying this into your spineml-2-brahms dir ($SPINEML_2_BRAHMS_DIR/Namespace)"
+    echo "Copying this into your spineml-2-brahms dir (${SPINEML_2_BRAHMS_DIR}/Namespace)"
     set -e
-    mkdir -p "$SPINEML_2_BRAHMS_DIR/Namespace"
-    cp -Ra /usr/lib/spineml-2-brahms/* "$SPINEML_2_BRAHMS_DIR/Namespace/"
+    mkdir -p "${SPINEML_2_BRAHMS_DIR}/Namespace"
+    cp -Ra /usr/lib/spineml-2-brahms/* "${SPINEML_2_BRAHMS_DIR}/Namespace/"
     set +e
 else
     # Check whether we need to build the spineml-2-brahms namespace
+    COS=$(cat "${SPINEML_2_BRAHMS_DIR}"/current_os)
     set -e # This tells bash to exit on any unsuccessful command (reverse with set +e)
-    if [ "x$(cat $SPINEML_2_BRAHMS_DIR/current_os)" = "x$OS" ]; then
+    if [ "x$COS" = "x$OS" ]; then
         echo "Tools compiled correctly"
     else
         echo "OS change detected, recompiling tools..."
         pwd
-        pushd tools
+	if [ ! -d "${SPINEML_2_BRAHMS_DIR}/tools" ]; then
+	    # cp tools from origin to working dir then compile
+	    cp -Ra "${CVRT_SCRIPT_DIR}/tools" "${SPINEML_2_BRAHMS_DIR}/"
+	    cp -Ra "${CVRT_SCRIPT_DIR}/include" "${SPINEML_2_BRAHMS_DIR}/"	    
+	fi
+        pushd "${SPINEML_2_BRAHMS_DIR}"/tools
         pushd allToAll/brahms/0/
         ./build
         popd
@@ -469,55 +481,55 @@ fi
 
 # Check if we have local xsl script which overrides the packaged/pre-installed xsl scripts:
 XSL_SCRIPT_PATH="/usr/share/spineml-2-brahms/xsl/SpineML_2_BRAHMS_write_script.xsl"
-if [ -f "$SPINEML_2_BRAHMS_DIR/xsl/SpineML_2_BRAHMS_write_script.xsl" ]; then
+if [ -f "${CVRT_SCRIPT_DIR}/xsl/SpineML_2_BRAHMS_write_script.xsl" ]; then
     echo "Using local version of the SpineML to BRAHMS xsl scripts because they exist."
-    XSL_SCRIPT_PATH="$SPINEML_2_BRAHMS_DIR/xsl/"
+    XSL_SCRIPT_PATH="${CVRT_SCRIPT_DIR}/xsl/"
 else
     XSL_SCRIPT_PATH="/usr/share/spineml-2-brahms/xsl/"
 fi
 
 # First check we have an experiment.xml file to work from.
 # Could use cmd-line arg $INPUT here for the experiment file.
-if [ ! -f "$OUTPUT_MODEL_DIR/$EXPERIMENT" ]; then
-    echo "No experiment description to work from in $OUTPUT_MODEL_DIR/$EXPERIMENT" >&2
+if [ ! -f "${OUTPUT_MODEL_DIR}/${EXPERIMENT}" ]; then
+    echo "No experiment description to work from in ${OUTPUT_MODEL_DIR}/${EXPERIMENT}" >&2
     echo "Exiting." >&2
     exit -1
 fi
 
 # Check we have xsltproc
 XSLTPROC_BIN=`which xsltproc`
-if [ "x$XSLTPROC_BIN" = "x" ]; then
+if [ "x${XSLTPROC_BIN}" = "x" ]; then
     echo "Couldn't find the xsltproc binary, exiting." >&2
     exit -1
 fi
 
 # Clean up any old reports (MOVE?)
-rm "$OUTPUT_DIR/rep*xml*" >/dev/null 2>&1
-rm "$OUTPUT_DIR/sys*" >/dev/null 2>&1
-rm "$OUTPUT_DIR/output_script" >/dev/null 2>&1
+rm "${OUTPUT_DIR}/rep*xml*" >/dev/null 2>&1
+rm "${OUTPUT_DIR}/sys*" >/dev/null 2>&1
+rm "${OUTPUT_DIR}/output_script" >/dev/null 2>&1
 
 # create the output script using an xsl translation and the experiment.xml file
-echo xsltproc -o "$OUTPUT_DIR/output.script" --stringparam hostos "$OS" \
-         "$XSL_SCRIPT_PATH/SpineML_2_BRAHMS_write_script.xsl" \
-         "$OUTPUT_MODEL_DIR/$EXPERIMENT"
-xsltproc -o "$OUTPUT_DIR/output.script" --stringparam hostos "$OS" \
-         "$XSL_SCRIPT_PATH/SpineML_2_BRAHMS_write_script.xsl" \
-         "$OUTPUT_MODEL_DIR/$EXPERIMENT"
+echo xsltproc -o "${OUTPUT_DIR}/output.script" --stringparam hostos "${OS}" \
+         "${XSL_SCRIPT_PATH}/SpineML_2_BRAHMS_write_script.xsl" \
+         "${OUTPUT_MODEL_DIR}/${EXPERIMENT}"
+xsltproc -o "${OUTPUT_DIR}/output.script" --stringparam hostos "${OS}" \
+         "${XSL_SCRIPT_PATH}/SpineML_2_BRAHMS_write_script.xsl" \
+         "${OUTPUT_MODEL_DIR}/${EXPERIMENT}"
 if [ "$?" -ne "0" ]; then
     echo "Failed to run xsltproc to produce the output script from your model. Exiting." >&2
     exit -1;
 fi
 
 # script permissions
-if [ -e "$OUTPUT_DIR/output.script" ]; then
-    chmod +x "$OUTPUT_DIR/output.script"
+if [ -e "${OUTPUT_DIR}/output.script" ]; then
+    chmod +x "${OUTPUT_DIR}/output.script"
 else
     echo "ERROR: conversion script not created - is xsltproc installed?" >&2
     exit -1
 fi
 
 # Configure environment variables for brahms
-if [ -z "$BRAHMS_NS" ]; then
+if [ -z "${BRAHMS_NS}" ]; then
     echo "Using defaults for BRAHMS_NS and SYSTEMML_INSTALL_PATH."
 
     if [ $OS = 'Linux32' ] || [ $OS = 'Linux64' ]; then
@@ -528,16 +540,16 @@ if [ -z "$BRAHMS_NS" ]; then
             BRAHMS_NS="/var/SystemML/Namespace"
         else
             # non-packaged brahms, assume SystemML folder in home directory.
-            export SYSTEMML_INSTALL_PATH="$HOME/SystemML"
-            BRAHMS_NS="$HOME/SystemML/Namespace"
+            export SYSTEMML_INSTALL_PATH="${HOME}/SystemML"
+            BRAHMS_NS="${HOME}/SystemML/Namespace"
         fi
     fi
 
     if [ $OS = 'OSX' ]; then
-	if [ -d $HOME/SystemML ]; then
+	if [ -d ${HOME}/SystemML ]; then
 	    # Use Brahms in home.
-	    export SYSTEMML_INSTALL_PATH="$HOME/SystemML"
-	    BRAHMS_NS="$HOME/SystemML/Namespace"
+	    export SYSTEMML_INSTALL_PATH="${HOME}/SystemML"
+	    BRAHMS_NS="${HOME}/SystemML/Namespace"
 	# Poss: elif [ -d /Applications/SystemML ]; then
 	    # Use installed Brahms
 	else
@@ -554,13 +566,13 @@ fi
 pushd "$OUTPUT_DIR"
 echo "In directory: " `pwd`
 echo "Execute: ./output.script $REBUILD_COMPONENTS $REBUILD_SYSTEMML $OUTPUT_MODEL_DIR $EXPERIMENT $BRAHMS_NS $SPINEML_2_BRAHMS_DIR  $OUTPUT_DIR $XSL_SCRIPT_PATH $VERBOSE_BRAHMS $NODES $NODEARCH $BRAHMS_NOGUI $ASSUME_COMPONENTS_PRESENT $BRAHMS_DEBUG"
-./output.script "$REBUILD_COMPONENTS" "$REBUILD_SYSTEMML" "$OUTPUT_MODEL_DIR" "$EXPERIMENT" "$BRAHMS_NS" "$SPINEML_2_BRAHMS_DIR" "$OUTPUT_DIR" "$XSL_SCRIPT_PATH"  "$VERBOSE_BRAHMS"  "$ASSUME_COMPONENTS_PRESENT" "$BRAHMS_DEBUG" "$BRAHMS_NOGUI" "$NODES" "$NODEARCH"
+./output.script "${REBUILD_COMPONENTS}" "${REBUILD_SYSTEMML}" "${OUTPUT_MODEL_DIR}" "${EXPERIMENT}" "${BRAHMS_NS}" "${SPINEML_2_BRAHMS_DIR}" "${OUTPUT_DIR}" "${XSL_SCRIPT_PATH}"  "${VERBOSE_BRAHMS}"  "${ASSUME_COMPONENTS_PRESENT}" "${BRAHMS_DEBUG}" "${BRAHMS_NOGUI}" "${NODES}" "${NODEARCH}"
 if [ "$?" -ne "0" ]; then
-    echo "Failed to run output.script on $EXPERIMENT. Falling at the last hurdle." >&2
+    echo "Failed to run output.script on ${EXPERIMENT}. Falling at the last hurdle." >&2
     exit -1;
 fi
 popd
 
 # Success!
 exit 0
-Execute: ./output.script false true /home/seb/src/SpineML_2_BRAHMS/temp/model experiment0.xml /home/seb/SystemML/Namespace /home/seb/src/SpineML_2_BRAHMS  /home/seb/src/SpineML_2_BRAHMS/temp /home/seb/src/SpineML_2_BRAHMS/xsl/ no     yes
+#Execute: ./output.script false true /home/seb/src/SpineML_2_BRAHMS/temp/model experiment0.xml /home/seb/SystemML/Namespace /home/seb/src/SpineML_2_BRAHMS  /home/seb/src/SpineML_2_BRAHMS/temp /home/seb/src/SpineML_2_BRAHMS/xsl/ no     yes
